sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  firefox: "46.0"
  hosts:
      - magento2.travis
language: php
php:
  - 7.1
git:
  depth: 5
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=3
    - NODE_JS_VERSION=8
    - MAGENTO_HOST_NAME="magento2.travis"
  matrix:
    - TEST_SUITE=static
    - TEST_SUITE=saucelabs
matrix:
  exclude:
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm
    - $HOME/node_modules
    - $HOME/yarn.lock
before_install: ./dev/travis/before_install.sh
install:
    - composer install --no-interaction --prefer-dist
    - composer require facebook/webdriver
    - composer require sauce/sausage
before_script:
    - ./dev/travis/before_script.sh
    - ./dev/saucelabs/before_script.sh
script:
    - if [ $TEST_SUITE == "saucelabs" ]; then php dev/tests/bootstrap.php; fi
